target 'HZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks 
  
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'SpotifyLogin', '~> 0.1'
  pod 'Parse'
  pod 'AFNetworking'
  pod 'BDBOAuth1Manager'
  pod 'AlamofireImage'
end
